name: Cloudflare Pages - Deploy

permissions:
    contents: read

on:
    pull_request:
        types: [closed]
        paths:
            - docs/**
            - .github/workflows/cloudflare-pages.yml
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Use Node.js - 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install Root Dependencies
              run: npm ci

            - name: Build Package
              run: npm run build

            - name: Deploy Docs
              working-directory: docs
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              run: |
                  npm ci
                  npm run deploy
